#!/usr/bin/env python3
"""Generate Apache RedirectMatch rules from content/posts frontmatter.

Maps each published post's old WordPress permalink (/YYYY/MM/DD/slug/) to
its new home (/log/slug/), for external bookmarks and search-engine links
that predate the move. Mirrors the pattern already hand-maintained in
wamason.com-ssl.conf, but generated rather than hand-written since fsgeek.ca
has ~100 posts instead of wamason.com's ~17.

Re-run this after publishing new posts (or changing any post's slug) and
redeploy deploy/fsgeek.ca-redirects.conf to the server.
"""
import re
from pathlib import Path

FM_RE = re.compile(r'^---\n(.*?)\n---\n\n(.*)$', re.DOTALL)
URL_RE = re.compile(r'^https://fsgeek\.ca/(\d{4})/(\d{2})/(\d{2})/([^/]+)/?$')


def main():
    root = Path('.')
    rules = []
    for f in sorted((root / 'content/posts').glob('*.html')):
        text = f.read_text(encoding='utf-8')
        m = FM_RE.match(text)
        fm_raw = m.group(1)
        fm = {}
        for line in fm_raw.splitlines():
            k, _, v = line.partition(':')
            v = v.strip()
            if v.startswith('"') and v.endswith('"'):
                v = v[1:-1]
            fm[k.strip()] = v
        if fm.get('status') != 'publish':
            continue
        url_m = URL_RE.match(fm.get('original_url', ''))
        if not url_m:
            continue
        y, mo, d, old_slug = url_m.groups()
        new_slug = f.stem
        rules.append((y, mo, d, old_slug, new_slug))

    lines = [
        '# Old WordPress date-based permalinks -> new /log/<slug>/ paths',
        '# Generated by scripts/gen-redirects.py -- do not hand-edit, regenerate instead',
        f'# {len(rules)} rules',
    ]
    for y, mo, d, old_slug, new_slug in rules:
        lines.append(
            f'RedirectMatch 301 "^/{y}/{mo}/{d}/{old_slug}/?$" "/log/{new_slug}/"'
        )

    out = root / 'deploy' / 'fsgeek.ca-redirects.conf'
    out.parent.mkdir(exist_ok=True)
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'wrote {len(rules)} redirect rules to {out}')


if __name__ == '__main__':
    main()
